version: "2"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studyhub_dev
      MYSQL_USER: diazzzu
      MYSQL_PASSWORD: pass1234
    volumes:
      - my_data_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

volumes:
  my_data_volume:
