version: "2"

services:
  app:
    #build: .
    command: >
            bash -c "echo $GCKEY && python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
    image: diazzzu/studyhub:studyhub_back
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
    environment:
      DEBUG: 'True'
      DBHOST: 'db'
      GOOGLE_APPLICATION_CREDENTIALS: 'google_cloud_key.json'
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studyhub_dev
      MYSQL_USER: diazzzu
      MYSQL_PASSWORD: pass1234
    volumes:
      - my_data_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

volumes:
  my_data_volume:
