version: "2"

services:
  app:
    #build: .
    command: >
            bash -c "python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
    image: diazzzu/studyhub:studyhub_back
    ports:
      - "8000:8000"
    restart: on-failure
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: 'google_cloud_key.json'

