version: "2"

services:
  app:
    image: diazzzu/studyhub:studyhub_back
    environment:
      - DB_PORT=3306
      - DB_NAME=studyhub_dev
      - DB_HOST=127.0.0.1
      - DB_USER=diazzzu
      - DB_PASSWORD=pass1234
      - DEBUG=False
      - GOOGLE_APPLICATION_CREDENTIALS=data/google_cloud_key.json
    command: >
            bash -c "python manage.py makemigrations && python manage.py migrate 
            && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .data:/studyhub/data
    network_mode: "host"
    ports:
      - "8000:8000"

    restart: on-failure