apiVersion: apps/v1
kind: Deployment
metadata:
  name: studyhub-deployment
  labels:
    app: studyhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studyhub
  template:
    metadata:
      labels:
        app: studyhub
    spec:
      containers:
        - image: diazzzu/studyhub:latest
          name: studyhub
          envFrom:
          - secretRef:
              name: adfs-secret
          - configMapRef:
              name: adfs-config
          - secretRef:
              name: db-secret
          - configMapRef:
              name: db-config
          - secretRef:
              name: moodle-secret
          - configMapRef:
              name: moodle-config
          - secretRef:
              name: studyhub-secret
          - configMapRef:
              name: studyhub-config
          ports:
            - containerPort: 8000