name: Docker build and deploy
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - 'master'
      - 'develop'
      - 'test'

jobs:
  docker-build-prod:
    uses: InnoStudyHub/back-end/.github/workflows/build_docker_image.yaml@develop
    with:
      tag: $GITHUB_RUN_NUMBER
      secret-env: prod