name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      DOCKER_LOGIN:
        required: true
      DOCKER_NAME:
        required: true
      DOCKER_PWD:
        required: true

jobs:
  docker-build:
    name: "Build and push docker"
    runs-on: [ ubuntu-latest ]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
      PWD: ${{ secrets.DOCKER_PWD }}
    steps:
      - name: Login to docker.io
        run: echo $PWD | docker login -u $LOGIN --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${{ inputs.tag }} .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${{ inputs.tag }}
