name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      secret-env:
        type: string
        required: true

jobs:
  docker-build:
    name: "Build and push docker"
    runs-on: [ ubuntu-latest ]
    environment: ${{ inputs.secret-env }}
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - run: |
          echo $LOGIN
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${{ inputs.tag }} .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${{ inputs.tag }}