name: python-linter

on:
  pull_request:
    types: [opened, edited, reopened]
  push:

jobs:
  pylint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linter
        run: |
          shopt -s globstar && pylint --django-settings-module=studyhub.settings */**/*.py
      - name: Results to summary
        run: |
          cat linter_report.txt >> $GITHUB_STEP_SUMMARY
