name: Django Test

on: push
jobs:
  test:
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: studyhub_dev
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DB_NAME: studyhub_dev
        DB_USER: test
        DB_PORT: 3306
        DB_PASSWORD: test
        DB_HOST: localhost
      run: |
        
        python manage.py test