name: Django Test

on: [push, pull_request]
jobs:
  test:
    env:
      DB_NAME: studyhub_dev
      DB_USER: test
      DB_PORT: 3306
      DB_PASSWORD: test
      DB_HOST: 127.0.0.1

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name:
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "GRANT ALL PRIVILEGES ON test_studyhub_dev.*  TO 'test'@'%';" studyhub_dev
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create and run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run Tests
        run: |
          coverage run --source='.' manage.py test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2