name: Django Test

on:
  pull_request:
    types: [opened, edited, reopened]
  push:

jobs:
  test:
    env:
      DB_NAME: studyhub_dev
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: 127.0.0.1
      DB_ROOT_PASSWORD: root

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: {{ env.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          cache: 'pip'
      - name:
        run: |
          mysql -h${{ env.DB_HOST }} -uroot -p${{ env.DB_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON test_${{ env.DB_NAME }}.*  TO '${{ env.DB_USER }}'@'%';" ${{ env.DB_NAME }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create and run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run Tests
        run: |
          coverage run --source='.' manage.py test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true