name: Docker build and deploy
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  docker-build:
    name: "Build and push docker"
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:studyhub_back .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:studyhub_back

  deploy:
    name: "Deploy to staging"
    runs-on: [ubuntu-latest]
    #needs: [docker-build]
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      PWD: ${{ secrets.DOCKER_PWD }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - uses: actions/checkout@master

      - name: Copy docker-compose to vm
        run: scp docker-compose.yaml staging:~/docker-compose.yaml

      - name: Run deploy.sh
        run: envsubst < deploy.sh | ssh staging sh
