name: Docker build and deploy
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  docker-build:
    name: "Build and push docker"
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:studyhub_back .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:studyhub_back

  docker-copy:
    name: Copy docker-compose
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yaml"
          target: "tmp"