name: Run tests on push
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  build_and_pub:
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:studyhub_back .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:studyhub_back